language: java
jdk:
  - openjdk14

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: './gradlew clean build'

notifications:
  email:
    recipients:
      - cooco119@gmail.com